### ISSUE TITLE
Reading Memory

### ISSUE THREAD

**Issue by mac10688** [AtmaWeapon/FFXIVSynthSolver#1]
Is this program reading the in game memory? If it could would that make the program more robust? Would you like for the functionality to read memory? It seems that this is not a bot and I am not sure if you want to take it that direction.

**Comment by AtmaWeapon** [comment]
Currently the program is not reading in game memory.  As for whether I would like that functionality, I'm taking a wait and see approach.  Yes it would be extremely useful as it would eliminate the need to Alt-Tab over to this application to enter the results of the random event between each interaction, and it would also eliminate the need to enter your stats.  That being said, I haven't studied the game's license yet, and we haven't seen what kind of approach SE will take.

Even if I do go down that route eventually, I don't intend to automate the tool so that it will perform the best actions for you automatically, it would be a read-only thing where it's only a convenience so that you don't have to enter the result of the synth at each step or your character's stats.

Do you have your own memory reading functionality that you're offering, or are you just wondering if I plan to go in this direction on my own?

In any case, my first order of business is correctness and speed.  To that end, the biggest priorities right now are constructing a good static evaluator (e.g. a state scoring function) that can rank states, and adding some tree optimizations (e.g. alpha-beta pruning) to reduce computation time.

**Comment by mac10688** [comment]
I am offering my services for reading memory. I have a successful prototype. SE would not know when a program is reading memory. Injecting DLL's is another story, but it isn't necessary. The correctness may be your biggest concern but my own project deals with reading memory structures of the game. Let's assume SE explicitly states that you can't read memory in the licenses, you would be unwilling to read memory?

**Comment by AtmaWeapon** [comment]
Can you send me an email?   ultimatecrust@gmail.com.  I think it's better to discuss privately.
